export const TOOLS = [
  {
    id: 0,
    name: 'Chat',
    description: 'Ask anything.',
    price: '0.01',
    priceDisplay: '0.01 USDC',
    priceWei: '10000', // 0.01 * 10^6 (USDC 6 decimals)
    icon: '💬',
    href: '/app/chat',
    color: '#3B82F6',
    toolId: 0,
  },
  {
    id: 1,
    name: 'Resume',
    description: 'Stand out.',
    price: '0.05',
    priceDisplay: '0.05 USDC',
    priceWei: '50000',
    icon: '📄',
    href: '/app/resume',
    color: '#C9A84C',
    toolId: 1,
  },
  {
    id: 2,
    name: 'Tweet',
    description: 'Go viral.',
    price: '0.01',
    priceDisplay: '0.01 USDC',
    priceWei: '10000',
    icon: '🐦',
    href: '/app/tweet',
    color: '#35D07F',
    toolId: 2,
  },
  {
    id: 3,
    name: 'Bio',
    description: 'Own your story.',
    price: '0.02',
    priceDisplay: '0.02 USDC',
    priceWei: '20000',
    icon: '👤',
    href: '/app/bio',
    color: '#8B5CF6',
    toolId: 3,
  },
];
